### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by mcavusoglumert** [mrgretwon/fut_sniping_bot#1]
Hello man, fiddling around with openCV to make such sniping bot, I came across yours and it seems to be an awesome looking one here. Will you be adding windows compatibility or could you lead me on how can I run this in windows?

Superb work from what I've seen, would love to test it out!

**Comment by mrgretwon** [comment]
Hi,
Thank you for your message. It is very motivating for further work. Tonight
I will add Windows compatibility and let you know when it's ready.

**Comment by mcavusoglumert** [comment]
Appreciated a lot. I'm a self-taught Python learner so it's really fascinating to see what someone has done which I'm trying to do. Great work once more!

**Comment by mrgretwon** [comment]
@mcavusoglumert
We have now windows compatibility. It would be great, if you can test it, and let me know your thoughts (I'm a Linux user).
