### ISSUE TITLE
Manually adding my user

### ISSUE THREAD

**Issue by erezhasson** [mrgretwon/fut_sniping_bot#3]
Hello, first of all thank you for sharing your autobuyer.
I'd like to know if theres a way to use the autobuyer with entering my user details and email details. I think many people here
will agree that entering our credentials is not the safest thing to do, and I want to know if there's another option.
Just to be clear: I'm not saying your autobuyer is sort of phishing, just want to be safe.
Thanks again for sharing.

**Comment by IngolfJensch** [comment]
this is open source why shouldn't it be safe?

**Comment by mrgretwon** [comment]
@erez32 
Hi,
You are right, good point. 
My intention was to automate the bot as much as possible, but I understand that some people may be afraid of the security of their accounts.
The functionality you request is very easy to do. I can just give you the option to enter your activation code manually, as well as your fut account details. For example, the bot will wait up to 5 minutes for data to be entered.

**Comment by erezhasson** [comment]
That will be awesome, thank you very much!

**Comment by mrgretwon** [comment]
@erez32 
The feature is done. Please, let me know what do you think.

**Comment by erezhasson** [comment]
Awesome! Thank you again.
